#!/usr/bin/env bash
set -euo pipefail

case "$1" in
	"w") read -r path && pape "$path" &>/dev/null;;
	"s") while read -r path; do cp "$path" "$(xdg-user-dir PICTURES)"; done;;
	"d") while read -r path; do rm "$path"; done;;
	"g") while read -r path; do setsid gimp "$path" >/dev/null 2>&1 & done;;
esac
