set encoding=utf8
syntax on
colorscheme wal
set background=dark
hi Normal ctermbg=NONE guibg=NONE
let g:limelight_conceal_ctermfg = 'darkgray'
let g:limelight_conceal_guifg = '#555555'
auto! User GoyoEnter Limelight
auto! User GoyoLeave Limelight!

set mouse=a
set nu rnu list lcs=eol:¬,tab:┊\ ,space:·
" set number
" set relativenumber
" set ruler
" set autoindent
" set smartindent
set nu rnu list
set spr sb
set nowrap ai

set vif=~/.vim/vif
set backup backupdir=~/.vim/bak/ backupskip=/tmp/*,/private/*
set swapfile directory=~/.vim/swp/
set undofile undodir=~/.vim/undo/

set omnifunc=ale#completion#OmniFunc
let g:ale_shell = '/bin/sh'
let g:ale_fix_on_save = 1
let g:ale_completion_enabled = 1

let g:ale_linters = {
"\ 'typescript': ['deno'],
"\ 'typescriptreact': ['deno'],
\ 'typescript': ['tsserver', 'eslint'],
\ 'typescriptreact': ['tsserver', 'eslint'],
\ 'rust': ['analyzer', 'cargo'],
\ 'wgsl': ['wgsl_analyzer'],
\}
let g:ale_fixers = {
"\ 'typescript': ['deno'],
"\ 'typescriptreact': ['deno'],
\ 'typescript': ['prettier'],
\ 'typescriptreact': ['prettier'],
\ 'rust': ['rustfmt'],
\ 'python': ['ruff_format'],
\ 'c': ['clang-format'],
\ 'cpp': ['clang-format']
\}

let g:taggedtemplate#tagSyntaxMap = {
\ "wgsl": "wgsl",
\ "html": "html",
\ "css":  "css"
\}
autocmd FileType javascript,javascriptreact,typescript,typescriptreact : call taggedtemplate#applySyntaxMap()
