export ZDOTDIR="$HOME/.config/zsh"

### Load config files for non-interactive sessions
if [ -d "$ZDOTDIR/env.d" ]; then
	for script in $ZDOTDIR/env.d/**/*.(zsh|bash|sh); do
		[ -r "$script" ] && . $script;
	done
fi
