let mapleader = ","

filetype plugin on
set viminfo+=n~/.vim/viminfo
set numberwidth=4
set modeline
set showcmd
set incsearch
set sidescroll=1
set sidescrolloff=200
set scrolloff=3
set laststatus=2
set splitbelow
set splitright
set notimeout
set backup
set backupdir=~/.vim/backup//
set swapfile
set directory=~/.vim/swap//
set undofile
set undodir=~/.vim/undo//
set t_Co=256

syntax on
colorscheme wal

" Use system clipboard
nn p "+]p
nn P "+]P
nn y "+y
nn Y "+Y
nn d "+d
nn D "+D
nn c "+c
nn C "+C
vn p "+]p
vn P "+]P
vn y "+y
vn Y "+Y
vn d "+d
vn D "+D
vn c "+c
vn C "+C

packloadall
silent! helptags ALL
