let mapleader = ","

filetype plugin on
set numberwidth=4
set showcmd
set incsearch
set sidescroll=1
set sidescrolloff=200
set scrolloff=3
set laststatus=2
set splitbelow
set splitright
set timeoutlen=100 ttimeoutlen=0
set backupdir=~/.vim/backup//
set directory=~/.vim/swap//
set undodir=~/.vim/undo//
set t_Co=256

syntax on
colorscheme wal

" Use system clipboard
nn p "+]p
nn P "+]P
nn y "+y
nn Y "+Y
nn d "+d
nn D "+D
nn c "+c
nn C "+C
vn p "+]p
vn P "+]P
vn y "+y
vn Y "+Y
vn d "+d
vn D "+D
vn c "+c
vn C "+C

au FileType * call mode#Detect()

let g:ale_fixers = {'javascript': ['eslint'],'go': ['go vet']}
let g:ale_completion_enabled = 1

packloadall
silent! helptags ALL
