#!/usr/bin/env bash
# TODO: Refactor handling of .links files:
# a .links file should have newline seperated destination:link pairs
# read them and create the symbolic links here

cd "$(dirname "$0")/.." || exit 1
DIR=$(pwd -P)
COLLECTIONS=$DIR/collections

### Functions
error (){
	printf "\r\e[38;0;31m➤ \033[0m%s\n" "$1";
}

success (){
	printf "\r\e[38;0;32m➤ \033[0m%s\n" "$1";
}

warn (){
	printf "\r\e[48;0;33m➤ \033[0m%s\n" "$1";
}

user (){
	printf "\r\e[48;0;34m➤ \033[0m%s\n" "$1";
}

helptext (){
	usage="Usage: $(basename "$0") [-f] [COLLECTION... || -a]
Install dotfile collections.
Example: script/link vim zsh

OPTIONS:
	-h
		Show this help text.
	-f
		Force installation by removing conflicting files.
	-a
		Install all collections.
COLLECTION:
	A subdirectory of collections/ containing a .links file
"
	printf "%s" "$usage"
}

containing_dir (){
	printf "%q\n" "$(basename "$(dirname "$1")")"
}

link_files (){
	# link_files ["SOURCE:DESTINATION"...]
	for file in "$@"; do
		while IFS=":" read -r source dest; do
			# short_source="(collections/$(containing_dir $source)/.links)"
			short_source="$(basename $dest) (collections/$(containing_dir $source)/$(basename $source))"
			ln_options=("-s")
			if [ ! -e "$dest" ]; then
				success "Linking $short_source to $dest"
			elif [ "$FORCE" = "1" ]; then
				success "Removing $dest and linking $short_source to $dest"
				[ -d "$dest" ] && rm -rf $dest
				ln_options+=('-fn')
			else
				warn "Skipping $short_source: $dest already exists"
				continue
			fi

			mkdir -p "$(dirname $dest)"
			ln_options+=("$source" "$dest")
			ln ${ln_options[@]}
		done <<< "$file"
	done
}



### Parse arguments
OPTIND=1

while getopts "hfa" o; do case $o in
	h) helptext && exit 0 ;;
	f) FORCE=1 ;;
	a) ALL=1 ;;
	*);;
esac done

shift $((OPTIND-1))
[ "${1:-}" = "--" ] && shift



# Exit if no collections specified
if [ ! "$ALL" = "1" ] && [ $# -eq 0 ]; then
	error "No collections provided"
	helptext
	exit 1
fi

### Prompt user for [-f]
if [ "$FORCE" = "1" ]; then
	read -rp "Dotfiles that are already present will be overwritten. Are you sure you want to continue? (y/N): " force_confirm
	[[ ! $force_confirm =~ [yY](es)* ]] && user "Cancelling" && exit 1
fi



### Find installers for user supplied collections
if [ $# -ne 0 ]; then
	for collection in "$@"; do
		if [ -r "$COLLECTIONS/$collection/.links" ]; then
			INSTALLERS="$INSTALLERS,$COLLECTIONS/$collection/.links"
		else
			error "Collection $collection: installer not found in $COLLECTIONS/$collection/.links"
			exit 1
		fi
	done
else
### Find installers for all collections
	for collection in "$COLLECTIONS"/*/.links; do
		[ -r "$collection" ] &&
		INSTALLERS="$INSTALLERS,$collection"
	done
fi



### Source links file
for links_file in ${INSTALLERS//,/ }; do
	if [ -r "$links_file" ]; then
		user "Installing collection $(containing_dir "${links_file}")"
		. "$links_file"
	fi
done
